// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d3407b5a413c307237d54cc92788903f83cd5d3c/koa-json/koa-json.d.ts
declare module "koa-json" {
    
    import * as Koa from "koa";
    
    function json(opts?:{
        
        /** 
         * default to pretty response [true]
        */
        pretty?: boolean,
        
        /**
         * optional query-string param for pretty responses [none]
         */
        param?: string,
        
        /**
         * JSON spaces [2]
         */
        spaces?: number
    }) : { (ctx: Koa.Context, next?: () => any): any } ;
    namespace json {}
    export = json;
}