// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/15337e2b6679415ad45841a2c6f9795366a64789/koa-favicon/koa-favicon.d.ts
declare module "koa-favicon" {

    import * as Koa from "koa";

    /**
     * Returns a middleware serving the favicon found on the given path.
     */
    function favicon(path: string, options?: {

        /**
         * cache-control max-age directive in ms, defaulting to 1 day.
         */
        maxage?: number;

    }): { (ctx: Koa.Context, next?: () => any): any };

    export = favicon;
}
